#!/usr/bin/env node
var https = require('https'),
    exec = require('child_process'),
    repoName = process.argv[2],
    githubUser = process.env.GITHUB_USERNAME,
    githubKey = process.env.GITHUB_KEY;

var jsonData = JSON.stringify({ name: repoName });

var headers = {
  'User-Agent': 'RepoKit/0.0.1',
  'Content-Type': 'application/json',
  'Content-Length': jsonData.length
};

var options = {
  hostname: 'api.github.com',
  path: '/user/repos',
  method: 'POST',
  auth: githubUser+':'+githubKey,
  headers: headers
};

var request = https.request(options, function(res){
  // set encoding
  // create response container
  // fill response container
  // grab and manipulate final response
  // handle errors
});