#!/usr/bin/env node
var https = require('https'),
    exec = require('child_process'),
    repoName = process.argv[2],
    githubUser = process.env.GITHUB_USERNAME,
    githubKey = process.env.GITHUB_KEY;

var jsonData = JSON.stringify({ name: repoName });

var headers = {
  'User-Agent': 'RepoKit/0.0.1',
  'Content-Type': 'application/json',
  'Content-Length': jsonData.length
};