#!/usr/bin/env node
var https = require('https'),
    exec = require('child_process'),
    repoName = process.argv[2],
    githubUser = process.env.GITHUB_USERNAME,
    githubKey = process.env.GITHUB_KEY;

var jsonData = JSON.stringify({ name: repoName });

var headers = {
  'User-Agent': 'RepoKit/0.0.1',
  'Content-Type': 'application/json',
  'Content-Length': jsonData.length
};

var options = {
  hostname: 'api.github.com',
  path: '/user/repos',
  method: 'POST',
  auth: githubUser+':'+githubKey,
  headers: headers
};

var request = https.request(options, function(res){
  res.setEncoding('utf-8');
  var chunkyString = '';
  res.on('data', function(chunk){
    chunkyString += chunk;
  });

  res.on('end', function(){
    var finalResponse = JSON.parse(chunkyString);
    exec('git init && git remote add origin '+finalResponse.clone_url);
  });

  res.on('error', function(err){
    console.error(err);
  });
});

request.write(jsonData);
request.end();